from vital_llm_reasoner.ensemble.member.ensemble_member import EnsembleMember


class GitHubMember(EnsembleMember):
    pass

# search a github repo using kgraphservice
# with kgraphservice set up to index the contents as
# KGDocument, potentially with underlying file node
# (KGCodeDocument is meant more for code generated by the LLM)
# KGDocument can include paths of the underlying files
# so this is searchable by the ensemble to get files within a particular directory/path


